[tool.ruff]
line-length = 88
show-fixes = true
src = ["hurricaneapi"]

[tool.ruff.lint]
select = [
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
]
ignore = ["F401"]
